#!/usr/bin/env ruby

require './lib/ultimate_guitar'
require 'yaml'

letter = UltimateGuitar::ArtistLetter.new(ARGV[0])
tabs = letter.artists.map(&:tabs)

UltimateGuitar::Logger.log("Found #{tabs.flatten.count} tabs.")
UltimateGuitar::Logger.log("Saving YAML dump.")
File.open("log/dumps/#{ARGV[0]}.yml", 'w') { |f| f.write(letter.artists.to_yaml) }
